# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maindialog.ui'
#
# Created: Mon May 25 18:05:24 2015
#      by: PyQt4 UI code generator 4.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainDialog(object):
    def setupUi(self, MainDialog):
        MainDialog.setObjectName("MainDialog")
        MainDialog.resize(294, 509)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainDialog.sizePolicy().hasHeightForWidth())
        MainDialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtGui.QVBoxLayout(MainDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameCircle = QtGui.QFrame(MainDialog)
        self.frameCircle.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameCircle.setFrameShadow(QtGui.QFrame.Raised)
        self.frameCircle.setObjectName("frameCircle")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frameCircle)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gviewCircle = QtGui.QGraphicsView(self.frameCircle)
        self.gviewCircle.setMinimumSize(QtCore.QSize(220, 220))
        self.gviewCircle.setObjectName("gviewCircle")
        self.horizontalLayout_2.addWidget(self.gviewCircle)
        self.verticalLayout.addWidget(self.frameCircle)
        self.lblFunction = QtGui.QLabel(MainDialog)
        self.lblFunction.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFunction.setObjectName("lblFunction")
        self.verticalLayout.addWidget(self.lblFunction)
        self.lblManual = QtGui.QLabel(MainDialog)
        self.lblManual.setObjectName("lblManual")
        self.verticalLayout.addWidget(self.lblManual)
        self.frameCalculator = QtGui.QFrame(MainDialog)
        self.frameCalculator.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameCalculator.setFrameShadow(QtGui.QFrame.Raised)
        self.frameCalculator.setObjectName("frameCalculator")
        self.gridLayout = QtGui.QGridLayout(self.frameCalculator)
        self.gridLayout.setObjectName("gridLayout")
        self.lblRadius = QtGui.QLabel(self.frameCalculator)
        self.lblRadius.setObjectName("lblRadius")
        self.gridLayout.addWidget(self.lblRadius, 0, 0, 1, 1)
        self.dsboxRadius = QtGui.QDoubleSpinBox(self.frameCalculator)
        self.dsboxRadius.setSingleStep(0.1)
        self.dsboxRadius.setObjectName("dsboxRadius")
        self.gridLayout.addWidget(self.dsboxRadius, 0, 1, 1, 1)
        self.lblDiameter = QtGui.QLabel(self.frameCalculator)
        self.lblDiameter.setObjectName("lblDiameter")
        self.gridLayout.addWidget(self.lblDiameter, 1, 0, 1, 1)
        self.dsboxDiameter = QtGui.QDoubleSpinBox(self.frameCalculator)
        self.dsboxDiameter.setMaximum(199.99)
        self.dsboxDiameter.setSingleStep(0.1)
        self.dsboxDiameter.setObjectName("dsboxDiameter")
        self.gridLayout.addWidget(self.dsboxDiameter, 1, 1, 1, 1)
        self.lblCircuit = QtGui.QLabel(self.frameCalculator)
        self.lblCircuit.setObjectName("lblCircuit")
        self.gridLayout.addWidget(self.lblCircuit, 2, 0, 1, 1)
        self.lblArea = QtGui.QLabel(self.frameCalculator)
        self.lblArea.setObjectName("lblArea")
        self.gridLayout.addWidget(self.lblArea, 3, 0, 1, 1)
        self.dsboxCircuit = QtGui.QDoubleSpinBox(self.frameCalculator)
        self.dsboxCircuit.setReadOnly(True)
        self.dsboxCircuit.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dsboxCircuit.setMaximum(999.99)
        self.dsboxCircuit.setObjectName("dsboxCircuit")
        self.gridLayout.addWidget(self.dsboxCircuit, 2, 1, 1, 1)
        self.dsboxArea = QtGui.QDoubleSpinBox(self.frameCalculator)
        self.dsboxArea.setReadOnly(True)
        self.dsboxArea.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dsboxArea.setMaximum(99999.99)
        self.dsboxArea.setObjectName("dsboxArea")
        self.gridLayout.addWidget(self.dsboxArea, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.frameCalculator)
        self.frameButtons = QtGui.QFrame(MainDialog)
        self.frameButtons.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameButtons.setFrameShadow(QtGui.QFrame.Raised)
        self.frameButtons.setObjectName("frameButtons")
        self.horizontalLayout = QtGui.QHBoxLayout(self.frameButtons)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbutCalculate = QtGui.QPushButton(self.frameButtons)
        self.pbutCalculate.setObjectName("pbutCalculate")
        self.horizontalLayout.addWidget(self.pbutCalculate)
        self.pbutReset = QtGui.QPushButton(self.frameButtons)
        self.pbutReset.setObjectName("pbutReset")
        self.horizontalLayout.addWidget(self.pbutReset)
        self.verticalLayout.addWidget(self.frameButtons)

        self.retranslateUi(MainDialog)
        QtCore.QMetaObject.connectSlotsByName(MainDialog)

    def retranslateUi(self, MainDialog):
        MainDialog.setWindowTitle(QtGui.QApplication.translate("MainDialog", "Circle Area Calculator", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFunction.setText(QtGui.QApplication.translate("MainDialog", "<html><head/><body><p>area = Pi * radius<span style=\" vertical-align:super;\">2</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lblManual.setText(QtGui.QApplication.translate("MainDialog", "Enter either the radius or the diameter.", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRadius.setText(QtGui.QApplication.translate("MainDialog", "Radius", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDiameter.setText(QtGui.QApplication.translate("MainDialog", "Diameter", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCircuit.setText(QtGui.QApplication.translate("MainDialog", "Circuit", None, QtGui.QApplication.UnicodeUTF8))
        self.lblArea.setText(QtGui.QApplication.translate("MainDialog", "Area", None, QtGui.QApplication.UnicodeUTF8))
        self.pbutCalculate.setText(QtGui.QApplication.translate("MainDialog", "Calculate", None, QtGui.QApplication.UnicodeUTF8))
        self.pbutReset.setText(QtGui.QApplication.translate("MainDialog", "Reset", None, QtGui.QApplication.UnicodeUTF8))

